# Gaia2TIC

In [30]:
import pandas as pd
import os
import re
from tqdm import tqdm

In [12]:
tic = pd.read_csv('../catalogs/tic_catalog_latest.txt',sep='\t')
cdips = pd.read_csv('../catalogs/CDIPS-S1-S55.txt',sep=';')

In [13]:
cdips = cdips[cdips.sector == 7]

---

In [14]:
tic

,tic_id,GAIAmag,gaiabp,gaiarp,d,e_d,plx,e_plx,Tmag,e_Tmag,Bmag,e_Bmag,Vmag,gaia_id
0,269273552,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-1.7450,0.1340,0.557,0.121,0.346457,NaN
1,175934060,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-1.6790,0.1680,0.530,0.142,NaN,NaN
2,459832522,NaN,NaN,NaN,11.2575,0.0684,88.830000,0.540000,-1.2540,0.1670,NaN,NaN,-0.103570,NaN
3,245873777,NaN,NaN,NaN,20.4332,0.3214,48.940000,0.770000,-1.2000,0.2090,0.375,0.208,0.872000,NaN
4,272314138,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-1.0430,0.1700,0.354,0.149,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13274418,1940269963,13.7786,14.5054,12.9391,3386.7700,259.8050,0.265597,0.022173,12.9999,0.0070,NaN,NaN,14.231900,1.806906e+18
13274419,1967770047,13.4299,NaN,NaN,1769.9700,109.0950,0.536508,0.033978,12.9999,0.6000,NaN,NaN,NaN,2.061423e+18
13274420,1969816527,13.7958,14.5527,12.8987,4073.1100,548.0250,0.212209,0.031830,12.9999,0.0062,NaN,NaN,14.298600,2.071522e+18
13274421,1980655433,13.4606,13.8160,12.9344,599.9670,7.4220,1.638110,0.020461,12.9999,0.0100,NaN,NaN,13.618900,2.236047e+18
13274422,2008395200,13.4129,13.7231,12.8921,2742.9800,107.1350,0.335322,0.014143,12.9999,0.0107,NaN,NaN,13.555800,1.971155e+18

In [22]:
match = cdips[cdips.dr2_source_id.isin(tic.gaia_id)]

In [24]:
cdips_lcs = pd.merge(tic,cdips,left_on='gaia_id',right_on='dr2_source_id',how='inner')

In [25]:
cdips_lcs.head()

,tic_id,GAIAmag,gaiabp,gaiarp,d,e_d,plx,e_plx,Tmag,e_Tmag,...,dr2_pmra,dr2_pmdec,dr2_phot_g_mean_mag,dr2_phot_rp_mean_mag,dr2_phot_bp_mean_mag,cluster,age,mean_age,reference_id,reference_bibcode
0,307458454,6.27897,6.33425,6.21093,213.312,2.2025,4.65980,0.048031,6.23591,0.0064,...,-12.606380,-8.733274,6.274475,6.210928,6.334248,NaN,NaN,NaN,Zari2018ums,2018A%26A...620A.172Z
1,32035258,6.23170,6.19374,6.34372,160.435,1.7555,6.20529,0.067679,6.36900,0.0061,...,20.966046,42.938136,6.226696,6.343724,6.193742,"nan,nan,IR_excess","nan,nan,nan",NaN,"Zari2018ums,Kerr2021,CottenSong2016","2018A%26A...620A.172Z,2021arXiv210509338K,2016..."
2,49243797,7.07705,7.71318,6.36249,736.905,20.1420,1.32937,0.036781,6.39580,0.0101,...,-4.371835,-1.268419,7.077050,6.362494,7.713182,"NGC_2287,NGC_2287,NGC 2287,NGC_2287,NGC_2287","8.24,8.23,8.01,8.23,8.23",8.19,"KounkelCovey2019,CantatGaudin2020a,Kounkel2020...","2019AJ....158..122K,2020A%26A...633A..99C,2020..."
3,50751274,6.54268,6.64708,6.41701,106.073,0.5430,9.39890,0.047890,6.43459,0.0062,...,-28.639623,-2.971500,6.542677,6.417010,6.647085,NaN,NaN,NaN,Zari2018ums,2018A%26A...620A.172Z
4,97356407,6.30069,6.25213,6.42461,326.086,7.6395,3.04055,0.071246,6.45530,0.0087,...,-11.613310,5.243574,6.296396,6.424612,6.252129,"nan,nan","nan,nan",NaN,"Zari2018ums,Kerr2021","2018A%26A...620A.172Z,2021arXiv210509338K"

In [31]:
directory = '../data/eleanor/s0007/'

filenames = os.listdir(directory)

# Dictionary to store matching filenames for each ID
id_to_files = {}

# Iterate over each ID in the DataFrame
for id_value in tqdm(cdips_lcs['tic_id']):
    pattern = re.compile(rf'{id_value}')
    matching_files = [filename for filename in filenames if re.search(pattern, filename)]
    id_to_files[id_value] = matching_files

100%|â–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆ| 19544/19544 [5:18:04<00:00,  1.02it/s]

In [53]:
import shutil
import glob
import numpy as np
import sys
sys.path.insert(1, '/Users/azib/Documents/open_source/nets2/stella/')
sys.path.insert(1, '/Users/azib/Documents/open_source/nets2/scripts/')
from utils import *
from tqdm import tqdm

In [39]:
os.makedirs('../data/eleanor/cdips-lcs', exist_ok=True)

# Loop through the dictionary and copy each file
for file_list in id_to_files.values():
    for file_name in file_list:
        file_name = os.path.join("../data/eleanor/s0007",file_name)
        shutil.copy(file_name, '../data/eleanor/cdips-lcs')

In [81]:
files2 = glob.glob('../data/eleanor/cdips-lcs/*.fits')
np.random.shuffle(files2)

fo = '../models/cdips/'
os.makedirs(fo,exist_ok=True)
t0 = []
t2 = []
tic = []
for i in tqdm(files2[0:5000]):
    lc, info = import_lightcurve(i)
    t = lc['TIME']
    t0.append(t[0] + 5)
    t2.append(t[-1] - 5)
    tic.append(info['TIC_ID'])
    f = lc['PCA_FLUX']/np.nanmedian(lc['PCA_FLUX'])
    fe = lc['FLUX_ERR']
    np.save(f"{fo}/{info['TIC_ID']}_sector07.npy", np.array([t,f,fe]))

100%|â–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆ| 5000/5000 [01:26<00:00, 57.52it/s]

### Creating a CDIPS stellar variability catalog
- Select a standard time (e.g: `t0 + 5`) and then make that the catalog.
- Then a second one from `t[-1] - 5`

In [82]:
data = pd.DataFrame(data=[tic,t0]).T
data.columns = ['TIC','tpeak']
data.TIC = data.TIC.astype(int)

In [83]:
data.to_csv('../catalogs/cdips.txt',index=None,sep=' ')